### ISSUE TITLE
grpc-create-metadata in package.json is the wrong version.

### ISSUE THREAD

**Issue by sorahn** [bojand/grpc-create-error#18]
all the grpc packages were updated to use @grpc/grpc-js, but this installs v3 of create-metadata and not v3.1 so the grpc package which v3 tries to import from is missing.

**Comment by sorahn** [comment]
@bojand looking at this some more, and I think the versions of `grpc-create-metadata` needs to depend on which version of Mali you're using.    The latest versions of Mail use `@grpc/grpc-js` which means that in order to use `grpc-create-error` we need to have the v4 of `grpc-create-metadata` but that doesn't match the version required by this package.

I think you need to release a v2 of this package that relies on v4 of `grpc-create-metadata`

**Comment by bojand** [comment]
should be fixed and published as v2.0.0

**Comment by sorahn** [comment]
Awesome, Thanks!
